---
functional:
  - Поле nickname должно иметь от 3-х до 16-ти символов 
  - Поле nickname может содержать буквы, цифры и подчеркивания и должно начинаться с латинской буквы
  - Поле email должно состоять из имени с любым количеством любых символов, символа @, домена с любым количеством любых символов, точки и указания национальной зоны
  - Поля password и password confirmation должны совпадать
  - Пользователь должен иметь возможность авторизироваться через GitHub 
  - Пользователь должен иметь возможность авторизироваться через Discord
  - Пользователь должен иметь возможность выбирать сложность новой игры от 1 до 4
  - Пользователь должен иметь возможность создавать игру с другими пользователями
  - Пользователь должен иметь возможность создавать игру с конкретным человеком
  - Пользователь должен иметь возможность создавать игру с ботом
  - Пользователь должен иметь возможность выбрать любую игру из предложенного списка
  - Пользователь должен иметь возможность фильтровать игры с помощью Tags
  - Пользователь должен иметь возможность откликаться на вызовы других участников
  - Пользователь должен иметь возможность смотреть на игры других участников 
  - Пользователь должен иметь возможность создавать игру с другими пользователями
  - Пользователь должен иметь возможность просматривать историю прохождения игры другими участниками
  - Пользователь должен иметь возможность просматривать историю пройденных им игр 
  - Пользователь должен иметь возможность сдаться
  - Пользователь должен иметь возможность перезагрузить игру
  - Пользователь должен иметь возможность выбрыть любой язык программированния из предложенного списка
  - Пользователь должен иметь возможность выбрать язык задания (русский или английский)
  - Пользователь должен иметь возможность добавлять новые задания для игр
  - При кажой новой игре пользователь должен иметь возсожность пройти гайд по пользованию платформой
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
implicit:
  - 
  - 
